<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> <!-- BOOTSTRAP CDN-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"> <!-- BOOTSTRAP ICONS CDN-->
    <title><?= $alert_title ?></title>
</head>
<body style="background-image: url('../../assets/contents/winter-background.jpg');
  background-size:cover;">
    
<div class="alert alert-<?= $alert_type ?>" role="alert">
   <?= $src_code ?>
</div>

</body>
</html>

