<div id="app">

    <nav_bar :contents="[{name:'Home',link:'menu.php'},{name:'Admin Pannel',link:'adminPannel.php'},{name:'Settings',link:'settings.php'},
    {name:'About',link:'about.php'}]" :buttons="[{name:'SignOut',link:'logout.php',class:'bi bi-box-arrow-right'}]"></nav_bar>

    <form_card :action="'settings.php'" :method="'post'" :inputs="[{name:'user',type:'text'},{name:'password',type:'password'},
    {name:'confirm_password',type:'password'},{name:'change_logo',type:'file'},{name:'link_logo',type:'text'}]" :values="['<?= $OldUser ?>','<?= $_SESSION["USER_PASSWORD"] ?>']" 
    :header="'Profile Settings'"
    :buttons="[{value:'save changes',type:'submit',class:'btn btn-primary',id:'submitButton'}]" :datacheck="NewAccountCheck" :toggles="['password']">
    
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#confirmDeletion" style="margin-left:2%">
    Delete Account</button><br><br>
    <div>* You must Retype you (old,new) password in order to<strong> confirm changes</strong>.<br>
    * You must use a<strong> unique name</strong> (shouldn't exist in database) for you account
    </div>
    <!--alerts-->
    <div class="alert alert-danger" role="alert" id="alert" style="display:none"></div>
    </form_card>

    <popup :id="'confirmDeletion'" :header="'Confirmation'" :content="'Are you sure you want to delete this account?'">
    
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a type="button" class="btn btn-primary" href="deleteAccount.php">Proceed</a>
        
    </popup>
</div>